alias ls='ls -lAh --group-directories-first --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias mv='mv -v'
alias cp='cp -v'
alias rm='rm -rv'
alias mkdir='mkdir -p'
#alias tmux='TERM=screen-256color-bce tmux'
alias grep='grep --color=auto'
alias v='vim'
alias vr='vim -R'
alias bc='bc -ql'
alias eq='/usr/bin/pulseaudio-equalizer-gtk'
